### ISSUE TITLE
[Front] 마지막 프론트엔드 수정-post, alert, mypage, pin, console

### ISSUE THREAD

**Issue by jamiep9rk** [codestates/Maplody#102]
### ISSUE
Group: client
Type: feature
Detail: 최종 배포 전 마지막 수정할 사항들입니다

### TODO
- [x] Alert 창 수정
- [x] 포스트 삭제
- [x] 중복된 아이디 나오면 alert창
- [x] 콘솔 다 지우기
- [x] 포스트 등록하면 바로 렌더링 되기
- [x] 마이페이지 포스트 숫자 바로 바뀌기
- [x] 마이페이지 숫자 많을 때 겹치는 부분 수정하기

### Estimated time
 8h
