### ISSUE TITLE
[Backend] aws token 로그인/회원가입 연결

### ISSUE THREAD

**Issue by anniemon** [codestates/Maplody#48]
### ISSUE
Group: `server`
Type: `feature`

### TODO
- [ ] aws에서 쿠키 사용하여 token 연결하는 법 알아보기
- [ ] server쪽 로그인 로직 같이 점검하기
- [ ] aws에서 token 사용하여 로그인/회원가입 배포하기

### Estimated time
`3h`
`3h`
`3h`

total: `9h`
